# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Answerer": "Roberta.ipynb"}

modules = ["models/roberta.py"]

doc_url = "https://willkunz13.github.io/ask_wiki/"

git_url = "https://github.com/willkunz13/ask_wiki/tree/main/"

def custom_doc_links(name): return None
