# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/Roberta.ipynb (unless otherwise specified).

__all__ = ['Answerer']

# Cell
from transformers import AutoModelForQuestionAnswering, AutoTokenizer, pipeline
from pathlib import Path
import yaml

# Cell

class Answerer():

    def __init__(self, model_name = "deepset/roberta-base-squad2"):
        self.model = AutoModelForQuestionAnswering.from_pretrained(model_name)
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.nlp = pipeline('question-answering', model=self.model, tokenizer=self.tokenizer)

    def __call__(self, input):
        return self.nlp(input)